---
name: Generate/update pr_comment
on:
  workflow_call:
    inputs:
      repository:
        description: Repository where the PR to be commented on resides
        type: string
        required: true
      action_run_id:
        description: Action run ID from which the job results shall be parsed
        type: string
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflows repo ↪️
        # Check out .github repo to gain access to scripts
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          repository: VoronDesign/.github
          persist-credentials: false
      - name: Setup python 3.11 🐍
        id: python311
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
        with:
          python-version: '3.11'
      - name: Install python packages 🛠️
        # Install required packages
        id: pip-install-packages
        run: |
          pip install requests
      - name: Generate PR Comment 📃
        id: generate_pr_comment
        # Generate the contents of the PR comment
        run: |
          python3 ${{ github.workspace }}/scripts/generate_pr_comment.py --repository=${{ inputs.repository }} --action_id=${{ inputs.action_run_id }} --out_file=${{ github.workspace }}/pr_comment.md
      - name: Post/Update PR Comment 📣
        uses: thollander/actions-comment-pull-request@8c77f42bbcc27c832a3a5962c8f9a60e34b594f3
        with:
          filePath: |
            ${{ github.workspace }}/pr_comment.md
          comment_tag: voron_users_ci
      - if: ${{ steps.generate_pr_comment.outputs.ALL_STEPS_OK == 'true' }}
        name: Add Ready for Review label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Ready for review']
            })
      - if: steps.generate_pr_comment.outputs.ALL_STEPS_OK == 'false' && contains(github.event.pull_request.labels.*.name, 'Ready for review')
        name: Remove Ready for Review label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['Ready for review']
            })

