---
name: Generate readme preview
on:
  workflow_call:
    inputs:
      subdirectory:
        description: Name of the directory in which the printer mods are located and
          where README.md is generated
        type: string
        required: true
      cache-key:
        description: Cache key where STL files to check are cached
        type: string
        required: true
      cache-directory:
        description: Cache subdirectory matching the cache key
        type: string
        required: false
        default: pr-files
      parent-job-name:
        description: Name of the parent job, so that this job can grab its own ID
        type: string
        required: true
    outputs:
      extended-outcome:
        description: Outcome of the step of interest
        value: ${{ jobs.run.outputs.extended-outcome }}
      numeric-job-id:
        description: Numeric ID of this Job
        value: ${{ jobs.run.outputs.numeric-job-id }}
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      extended-outcome: ${{ steps.preview-readme.outcome }}
      numeric-job-id: ${{ steps.output_job_id.outputs.job_id }}
    steps:
      - name: Checkout workflows repo ↪️
        # Check out .github repo to gain access to scripts
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          repository: VoronDesign/.github
          persist-credentials: false
      - name: Get repository files cache 🧰
        # Get cached PR files
        uses: actions/cache/restore@627f0f41f6904a5b1efbaed9f96d9eb58e92e920
        id: get-repo-cache
        with:
          path: ${{ github.workspace }}/${{ inputs.cache-directory }}
          key: ${{ inputs.cache-key }}
      - name: Setup python 3.11 🐍
        id: python311
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
        with:
          python-version: '3.11'
      - name: Install python packages 🛠️
        id: pip-install-packages
        run: |
          pip install pyyaml
      - name: Preview README.md 📃
        id: preview-readme
        # Preview the new readme file
        run: |-
          cd ${{ github.workspace }}/${{ inputs.cache-directory }}/${{ inputs.subdirectory }}
          export PREVIEW=true
          python ${{ github.workspace }}/scripts/generate_readme.py
      - if: ${{ always() && inputs.parent-job-name != ''}}
        name: Output Job ID ⬆️
        id: output_job_id
        env:
          INPUT_JOB_NAME: ${{ inputs.parent-job-name }} / ${{ github.job }}
          INPUT_GITHUB_TOKEN: ${{ github.token }}
        run: bash scripts/get_job_id.sh
